spring:
  data:
    mongodb:
      authentication-database: admin
      username: getir
      password: p_getir
      database: getir-bookstore
      port: 27017
      host: ${DATASOURCE_HOST:localhost}


auth:
  userName: ahmet
  userPass: p_ahmet
  secret: 04FFE52F8C9055ED402C2091AABF358281C63BCF5E6D6780B7BD34CFF50EC97A
